// <auto-generated />
namespace InsuranceCar_WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changekeyagainx2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changekeyagainx2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208291216228_change key again x2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
